#!/bin/bash

# Script d'intégration continue pour mettre à jour les statistiques automatiquement
# Utilisation: ./scripts/ci-update-stats.sh

set -e

# Couleurs pour l'affichage
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Intégration Continue - Mise à jour des statistiques${NC}"
echo ""

# Étape 1: Exécuter les tests et vérifier qu'ils passent
echo -e "${BLUE}[1/4] Exécution des tests...${NC}"
if npm test --silent >/dev/null 2>&1; then
    echo -e "${GREEN}✅ Tous les tests passent${NC}"
else
    echo -e "${RED}❌ Des tests échouent - arrêt du processus${NC}"
    exit 1
fi

# Étape 2: Vérifier le lint
echo -e "${BLUE}[2/4] Vérification du code style...${NC}"
if npm run lint --silent >/dev/null 2>&1; then
    echo -e "${GREEN}✅ Code style conforme${NC}"
else
    echo -e "${RED}❌ Erreurs de lint détectées - arrêt du processus${NC}"
    exit 1
fi

# Étape 3: Mise à jour des statistiques dans tous les fichiers
echo -e "${BLUE}[3/4] Mise à jour des statistiques...${NC}"
./scripts/update-docs-stats.sh

# Étape 4: Vérifier si des modifications ont été apportées
echo -e "${BLUE}[4/4] Vérification des changements...${NC}"

if git diff --quiet; then
    echo -e "${GREEN}✅ Statistiques déjà à jour${NC}"
else
    echo -e "${YELLOW}📝 Statistiques mises à jour, ajout des changements...${NC}"
    
    # Afficher les changements
    echo -e "${BLUE}📋 Changements détectés:${NC}"
    git diff --stat --color=always
    
    # Ajouter les changements
    git add -A
    
    # Proposer un commit automatique 
    echo ""
    echo -e "${YELLOW}💡 Suggestion de commit:${NC}"
    echo "   git commit -m \"📊 Update dynamic statistics in documentation\""
    echo ""
    
    read -p "Voulez-vous commiter automatiquement ces changements? (y/N): " -n 1 -r
    echo
    
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git commit -m "📊 Update dynamic statistics in documentation

- Tests: $(./scripts/generate-badges.sh | grep 'Tests passed:' | cut -d':' -f2 | xargs)
- Coverage: $(./scripts/generate-badges.sh | grep 'Coverage:' | cut -d':' -f2 | xargs)
- Auto-generated by CI script"
        echo -e "${GREEN}✅ Changements commités automatiquement${NC}"
    else
        echo -e "${YELLOW}⚠️  Changements préparés mais non commités${NC}"
        echo "   Utilisez 'git commit' quand vous serez prêt"
    fi
fi

echo ""
echo -e "${GREEN}🎉 Intégration continue terminée avec succès !${NC}"

# Afficher les statistiques finales
echo ""
echo -e "${BLUE}📊 Statistiques actuelles:${NC}"
source ./scripts/generate-badges.sh >/dev/null 2>&1
echo "   - Test suites: $DYNAMIC_TEST_SUITES"  
echo "   - Tests: $DYNAMIC_TESTS_PASSED"
echo "   - Coverage: $DYNAMIC_COVERAGE%"
echo "   - Status: Ready for deployment ✨"